### ISSUE TITLE
No consistency in how library dependencies are expressed

### ISSUE THREAD

**Issue by m50d** [PembrokeNS/sakusen#12]
Sometimes we use a suffix variable, sometimes we don't. Sometimes we use pkg-config, sometimes we use `-l` directly. To solve this properly we would need a `Makefile` linter or similar that runs as part of the build process.

**Comment by jbytheway** [comment]
I think things are as consistent as can be expected.  We are consuming each library in the manner most suited to it.  There's a lack of consistency only because libraries present themselves inconsistently.  If we switched to e.g. a CMake build (which is probably a good idea for other reasons) it might improve a little, but in my experience these things are always messier than one would hope.

**Comment by m50d** [comment]
I think I filed this after seeing the same library linked via `pkg-config --libs` and explicit `-l<name>` in different parts of the tree, which is definitely wrong. 100% consistency is perhaps too much to ask for, but we could have a look and put as much as we can onto `pkg-config`, say.

**Comment by jbytheway** [comment]
Ran this as a quick check
```
$ find -name Makefile.local | xargs awk '/^LIBS/{on=1}{if (on) print}/[^\\]$/{on=0}' 
LIBS := -lboost_python$(BOOST_LIB_SUFFIX)
LIBS := -lboost_filesystem -lboost_system -lltdl
LIBS = -ldl
LIBS = \
        -lboost_unit_test_framework$(BOOST_LIB_SUFFIX) \
        -lboost_system$(BOOST_LIB_SUFFIX) \
        -lboost_filesystem$(BOOST_LIB_SUFFIX)
LIBS := -lboost_filesystem -lboost_system
LIBS := -lpng
LIBS += -lltdl
LIBS = -lboost_unit_test_framework$(BOOST_LIB_SUFFIX)
LIBS = -lmhash \
        -lboost_filesystem$(BOOST_LIB_SUFFIX) -lboost_system$(BOOST_LIB_SUFFIX)
LIBS := -lrt -lboost_filesystem -lboost_system
LIBS += -lltdl
LIBS := -lboost_filesystem -lboost_system
LIBS += -lreadline
LIBS += -licuuc
LIBS += -lSDL
LIBS += `pkg-config --libs pangocairo`
LIBS := `pkg-config --libs libglademm-2.4` -lboost_filesystem -lboost_system
```
I don't see the particular issue you mentioned, but indeed the Boost suffix is used inconsistently, which is potentially bad (we don't want to link against both versions of a Boost library; I'm rather surprised this hasn't already caused a linker error).  A linter for that might be worthwhile.

**Comment by jbytheway** [comment]
I checked and it transpires that we have never had anything that automatically added a non-empty BOOST_LIB_SUFFIX, it can only get set by humans, so that's probably why this inconsistency is not causing a problem.

**Comment by m50d** [comment]
Yeah I fixed the specific instance at the time, this issue was to remind me to do a more general check.

If the BOOST_LIB_SUFFIX is unused, we should remove it and then close this issue?

**Comment by jbytheway** [comment]
I wish I remembered exactly why I added it originally.  I suspect because I was on a platform where only the -mt versions existed.  But I guess we have evidence that the requirement hasn't arisen recently, and we're not maintaining it properly, so removing the feature is certainly reasonable.  It's easy enough to revisit if it turns out to be needed once more.
